# Role variables.
system:
  yum:
    conf_dir: /etc/yum.repos.d
  network:
    kernel:
      conf_dir: /etc/sysctl.d
kubernetes:
  organization: sloopstash
  stack: null
  release_version: 21
  conf_dir: /etc/kubernetes
  client:
    conf_dir: /home/vagrant/.kube
  kubelet:
    conf_dir: /etc/sysconfig/kubelet
  network:
    kubelet: 
      conf_dir: /etc/sysconfig
    flannel: https://raw.githubusercontent.com/sloopstash/kickstart-kubernetes/master/cni/flannel/main.yml