# Role variables.
kubernetes:
  version: 1.19.4
  starter_kit_dir: /opt/kickstart-kubernetes
  docker:
    conf_dir: /etc/docker
  client:
    conf_dir: /home/vagrant/.kube
  network:
    flannel: https://raw.githubusercontent.com/sloopstash/kickstart-kubernetes/master/cni/flannel/main.yml
    master_ip: 192.168.101.62
    worker_ip: 192.168.101.66