# Reload Systemd service.
- name: Reload Systemd service
  ansible.builtin.systemd:
    daemon_reload: true
  tags:
    - configure

# Restart Docker CRI service.
- name: Restart Docker CRI service
  ansible.builtin.systemd:
    name: cri-docker.service
    state: restarted
  tags:
    - configure
