# Restart Docker.
- name: Restart Docker
  command: systemctl restart docker.service
  tags:
    - restart

# Restart cri-docker.
- name: Restart cri-docker service
  command: systemctl restart cri-docker.service
  tags:
    - restart
