# Reload Systemd service.
- name: Reload Systemd service
  ansible.builtin.systemd:
    daemon_reload: true
  tags:
    - configure

# Restart Docker service.
- name: Restart Docker service
  ansible.builtin.systemd:
    name: docker.service
    state: restarted
  tags:
    - configure
