# Install Nginx.
- name: Install Nginx
  ansible.builtin.yum:
    name: https://nginx.org/packages/rhel/7/x86_64/RPMS/nginx-{{nginx.release_version}}-1.el7_4.ngx.x86_64.rpm
    state: present
  tags:
    - setup

# Create Nginx directories.
- name: Create Nginx directories
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    recurse: true
    mode: 0700
  loop:
    - "{{nginx.root_dir}}"
    - "{{nginx.log_dir}}"
    - "{{nginx.conf_dir}}"
    - "{{nginx.script_dir}}"
    - "{{nginx.system_dir}}"
    - "{{app.source_dir}}"
  tags:
    - setup
