# Remove Firewall service.
- name: Remove Firewall service
  ansible.builtin.systemd:
    name: firewalld.service
    enabled: false
    state: stopped
  tags:
    - setup

# Set SELinux in permissive mode.
- name: Set SELinux in permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  tags:
    - setup

# Disable Linux swap memory (temporary).
- name: Disable Linux swap memory (temporary)
  ansible.builtin.command:
    cmd: swapoff -a
  tags:
    - setup

# Enable bridge netfilter Linux kernel module.
- name: Enable bridge netfilter Linux kernel module
  community.general.modprobe:
    name: br_netfilter
    state: present
  tags:
    - setup
