# Set timezone to UTC.
- name: Set timezone to UTC
  community.general.timezone:
    name: UTC
  tags:
    - setup

# Update installed packages.
# - name: Update installed packages
#   ansible.builtin.yum:
#     name: '*'
#     state: latest
#     update_cache: yes
#   tags:
#     - setup

# Disable Firewall service at boot.
- name: Disable Firewall service at boot
  ansible.builtin.systemd:
    name: firewalld.service
    enabled: false
  when:
    - ansible_distribution == 'AlmaLinux'
    - ansible_distribution_major_version == 9
  tags:
    - setup

# Set SELinux in permissive mode.
- name: Set SELinux in permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  tags:
    - setup

# Disable Linux swap memory (temporary).
- name: Disable Linux swap memory (temporary)
  ansible.builtin.command:
    cmd: swapoff -a
  tags:
    - setup

# Disable Linux swap memory (permanent).
- name: Disable Linux swap memory (permanent)
  ansible.posix.mount:
    name: swap
    fstype: swap
    state: absent
  tags:
    - setup

# Enable bridge netfilter Linux kernel module.
- name: Enable bridge netfilter Linux kernel module
  community.general.modprobe:
    name: br_netfilter
    state: present
  tags:
    - setup
