# Remove Firewall service.
- name: Remove Firewall service
  ansible.builtin.systemd:
    name: firewalld.service
    enabled: no
    state: stopped
  tags:
    - setup

# Set SELinux in permissive mode.
- name: Set SELinux in permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  tags:
    - setup

# Disable Linux swap memory (temporary).
- name: Disable Linux swap memory (temporary)
  ansible.builtin.command:
    cmd: swapoff -a
  register: status
  failed_when:
    - status.rc != 0
    - status.rc != 1
  tags:
    - setup

# Enable bridge netfilter Linux kernel module (temporary).
- name: Enable bridge netfilter Linux kernel module (temporary)
  ansible.builtin.command:
    cmd: modprobe br_netfilter
    removes: /bin/systemd
  register: status
  failed_when:
    - status.rc != 0
    - status.rc != 1
  tags:
    - setup
