# pull core image.
FROM amazonlinux:2

# install system packages.
RUN set -x \
  && yum update -y \
  && yum install -y wget vim net-tools initscripts gcc make tar \
  && yum install -y python-devel python-setuptools \
  && easy_install supervisor pip \
  && mkdir /etc/supervisord.d

# install openssh server and passwd.
RUN yum install -y openssh-server passwd

# configure openssh server.
RUN mkdir /var/run/sshd
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
RUN sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config

# configure openssh user.
RUN mkdir /root/.ssh
RUN touch /root/.ssh/authorized_keys
RUN touch /root/.ssh/config
RUN echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" >> /root/.ssh/config
RUN chmod 400 /root/.ssh/config
ADD secrets/ansible-node.pub /root/.ssh/authorized_keys

# cleanup history.
RUN history -c