# Install Cgroup library.
- name: Install Cgroup library
  ansible.builtin.yum:
    name: "{{download_url}}"
    disable_gpg_check: true
    state: present
  vars:
    architecture: "{{'aarch64' if ansible_architecture == 'arm64' else 'x86_64'}}"
    cgroup_release_version: "{{docker_cri.cgroup.release_version}}"
    cgroup_enterprise_linux: "{{docker_cri.cgroup.enterprise_linux}}"
    download_url: "https://repo.almalinux.org/almalinux/{{cgroup_enterprise_linux}}/BaseOS/{{architecture}}/os/Packages/libcgroup-{{cgroup_release_version}}-19.el{{cgroup_enterprise_linux}}.{{architecture}}.rpm"
  tags:
    - setup

# Download and extract Docker CRI.
- name: Download and extract Docker CRI
  ansible.builtin.unarchive:
    src: "{{download_url}}"
    dest: /tmp
    owner: root
    group: root
    remote_src: yes
    creates: "{{archive_path}}"
  vars:
    architecture: "{{'arm64' if ansible_architecture == 'arm64' else 'amd64'}}"
    release_version: "{{docker_cri.release_version}}"
    download_url: "https://github.com/Mirantis/cri-dockerd/releases/download/v{{release_version}}/cri-dockerd-{{release_version}}.{{architecture}}.tgz"
    archive_path: "/tmp/cri-dockerd-{{release_version}}.{{architecture}}.tgz"
  tags:
    - setup

# Install Docker CRI.
- name: Install Docker CRI
  ansible.builtin.copy:
    src: "{{source_dir}}/cri-dockerd"
    dest: /usr/bin/cri-dockerd
    owner: root
    group: root
    mode: 0755
    backup: false
    remote_src: true
  vars:
    source_dir: /tmp/cri-dockerd
  tags:
    - setup
