# Install system packages.
- name: Install system packages
  ansible.builtin.yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  tags:
    - setup

# Add Docker repository to package manager source list.
- name: Add Docker repository to package manager source list
  ansible.builtin.template:
    src: yum.repo.j2
    dest: "{{yum_conf_dir}}/docker.repo"
    owner: root
    group: root
    mode: 0600
    backup: false
  vars:
    yum_conf_dir: "{{system.yum.conf_dir}}"
  tags:
    - setup

# Install Docker, Docker client, and Containerd.
- name: Install Docker, Docker client, and Containerd
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  tags:
    - setup

# Enable Docker service at boot.
- name: Enable Docker service at boot
  ansible.builtin.systemd:
    name: docker.service
    enabled: true
  tags:
    - setup
