# Start Docker.
- name: Start Docker
  become: true
  command: systemctl start docker.service
  tags:
    - start

# Start cri-docker.
- name: Start cri-docker service
  become: true
  command: systemctl start cri-docker.service
  tags:
    - start