# Apply Linux kernel params.
- name: Apply Linux kernel params
  ansible.builtin.command:
    cmd: "sysctl -p {{kernel_conf_path}}"
  register: status
  failed_when:
    - status.rc != 0
    - status.rc != 1
    - status.rc != 255
  vars:
    organization: "{{system.organization}}"
    kernel_conf_path: "/etc/sysctl.d/90-{{organization}}.conf"
  tags:
    - configure
