# Configure Kubelet.
- name: Configure Kubelet
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/kubelet
    regexp: "^KUBELET_EXTRA_ARGS="
    line: "KUBELET_EXTRA_ARGS=--node-ip={{ansible_eth1.ipv4.address}}"
    state: present
  notify:
    - Restart Kubelet
  tags:
    - configure

# Initialize Kubernetes cluster.
- name: Initialize Kubernetes cluster
  ansible.builtin.command:
    cmd: "kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ansible_eth1.ipv4.address}} --cri-socket=unix:///var/run/cri-dockerd.sock"
    creates: "{{admin_conf_path}}"
  run_once: true
  when:
    - inventory_hostname in groups['kubernetes_master']
    - "'-mtr-1' in inventory_hostname"
  vars:
    admin_conf_path: "{{kubernetes.conf_dir}}/admin.conf"
  tags:
    - configure

# Configure Kubernetes client with admin user credentials.
- name: Configure Kubernetes client with admin user credentials
  ansible.builtin.copy:
    src: "{{admin_conf_path}}"
    dest: "{{client_conf_path}}"
    owner: "{{system_user}}"
    group: "{{system_group}}"
    mode: 0600
    backup: false
    remote_src: true
  when:
    - inventory_hostname in groups['kubernetes_master']
    - "'-mtr-1' in inventory_hostname"
  vars:
    system_user: "{{system.user}}"
    system_group: "{{system.group}}"
    admin_conf_path: "{{kubernetes.conf_dir}}/admin.conf"
    client_conf_path: /home/{{system_user}}/.kube/config
  tags:
    - configure

# Create Flannel network in Kubernetes cluster.
- name: Create Flannel network in Kubernetes cluster
  ansible.builtin.command:
    cmd: "kubectl apply -f {{kubernetes.cni.flannel.template_url}}"
  become: true
  become_user: "{{system_user}}"
  run_once: true
  when:
    - inventory_hostname in groups['kubernetes_master']
    - "'-mtr-1' in inventory_hostname"
  vars:
    system_user: "{{system.user}}"
  tags:
    - configure

# Create bootstrap token in Kubernetes cluster.
- name: Create bootstrap token in Kubernetes cluster
  ansible.builtin.command:
    cmd: kubeadm token create --print-join-command
  run_once: true
  when:
    - inventory_hostname in groups['kubernetes_master']
    - "'-mtr-1' in inventory_hostname"
  register: node_join_command
  tags:
    - configure

# Join Kubernetes worker node to the cluster.
- name: Join Kubernetes worker node to the cluster
  ansible.builtin.command:
    cmd: "{{hostvars['sloopstash-stg-k8s-mtr-1']['node_join_command']['stdout']}} --cri-socket=unix:///var/run/cri-dockerd.sock"
    creates: "{{conf_dir}}/kubelet.conf"
  run_once: true
  when: inventory_hostname in groups['kubernetes_worker']
  vars:
    environment: "{{kubernetes.environment}}"
    conf_dir: "{{kubernetes.conf_dir}}"
  tags:
    - configure
