# Enable netfilter Linux kernel module.
- name: Enable netfilter Linux kernel module
  become: true
  command: modprobe br_netfilter
  tags:
    - setup

# Set required network and swap Linux kernel params.
- name: Set required network and swap Linux kernel params
  become: true
  copy:
    src: kernel.conf
    dest: "{{system.network.kernel.conf_dir}}/kubernetes.conf"
    owner: root
    group: root
    mode: 0600
  tags:
    - setup

# Apply required network and swap Linux kernel params.
- name: Apply required network and swap Linux kernel params
  become: true
  command: sysctl --system
  tags:
    - setup

# Add Kubernetes repository to package manager source list.
- name: Add Kubernetes repository to package manager source list
  become: true
  copy:
    src: yum.repo
    dest: "{{system.yum.conf_dir}}/kubernetes.repo"
    owner: root
    group: root
    mode: 0600
  tags:
    - setup

# Install Kubernetes packages from repository.
- name: Install Kubernetes packages from repository
  become: true
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: kubernetes
  tags:
    - setup

# Create Kubernetes client configuration directory.
- name: Create Kubernetes client configuration directory
  become: true
  file:
    path: "{{kubernetes.client.conf_dir}}"
    state: directory
    owner: vagrant
    group: vagrant
    recurse: true
    mode: 0755
  run_once: true
  when: inventory_hostname in groups['kubernetes_master']
  tags:
    - setup

