# Add Kubernetes repository to package manager source list.
- name: Add Kubernetes repository to package manager source list
  ansible.builtin.template:
    src: yum.repo.j2
    dest: "{{yum_conf_dir}}/kubernetes.repo"
    owner: root
    group: root
    mode: 0600
    backup: false
  vars:
    release_version: "{{kubernetes.release_version}}"
    yum_conf_dir: "{{system.yum.conf_dir}}"
  tags:
    - setup

# Install Kubernetes agent, Kubernetes admin, and Kubernetes client.
- name: Install Kubernetes agent, Kubernetes admin, and Kubernetes client
  ansible.builtin.yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    disable_excludes: kubernetes
    state: present
  tags:
    - setup

# Enable Kubelet service at boot.
- name: Enable Kubelet service at boot
  ansible.builtin.systemd:
    name: kubelet.service
    enabled: yes
  tags:
    - setup
